// CI/CD renderer: decision-ledger JSON -> workflow YAML.
//
// See docs/architecture/cicd-autosetup.md:
// - docs/contracts/cicd-answers.json is the source of truth and YAML is generated.
//   This file writes but never reads YAML, so no YAML parser dependency is needed.
// - Structural and security safeguards are enforced here rather than delegated to
//   callers. A ledger that violates an invariant fails hard and is never repaired silently.

import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { createHash, randomUUID } from "node:crypto";
import { basename, dirname, extname, isAbsolute, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { projectRoot } from "../quality/lib/files.mjs";

const ROOT = projectRoot();
const ANSWERS_PATH = resolve(ROOT, "docs/contracts/cicd-answers.json");
const WORKFLOW_DIRECTORY = resolve(ROOT, ".github/workflows");
export const MANAGED_MARKER = "# managed-by: scripts/cicd/render.mjs";
export const RELEASE_PLEASE_CONFIG_NAME = "release-please-config.json";
export const RELEASE_PLEASE_MANIFEST_NAME = ".release-please-manifest.json";
const RELEASE_PLEASE_CONFIG_PATH = resolve(ROOT, RELEASE_PLEASE_CONFIG_NAME);
const RELEASE_PLEASE_MANIFEST_PATH = resolve(ROOT, RELEASE_PLEASE_MANIFEST_NAME);
const RELEASE_PLEASE_ACTION =
  "googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7";
const SEMVER =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/;
const SUPPORTED_RELEASE_TYPES = new Set(["node", "simple"]);
const MANAGED_CONFIG_DIGEST = "managed-config-sha256";
const RELEASE_CONFIG_FIELDS = new Set([
  "$schema",
  "bootstrap-sha",
  "extra-files",
  "group-pull-request-title-pattern",
  "include-component-in-tag",
  "include-v-in-tag",
  "packages",
  "pull-request-title-pattern",
  "release-type",
  "skip-github-release",
  "version-file",
]);
const RELEASE_PACKAGE_FIELDS = new Set([
  "extra-files",
  "release-type",
  "skip-github-release",
  "version-file",
]);

// ---------------------------------------------------------------------------
// Restricted YAML serializer for maps, sequences, strings, numbers, booleans,
// and block scalars. The controlled output makes the same JSON byte-stable across
// machines, so drift detection can compare generated bytes directly.
// ---------------------------------------------------------------------------

// YAML 1.1 reads these bare literals as booleans or null, so quote string values.
const RESERVED_PLAIN = new Set([
  "true", "false", "yes", "no", "on", "off", "null", "~", "y", "n",
]);

function needsQuote(text) {
  if (text === "") return true;
  if (RESERVED_PLAIN.has(text.toLowerCase())) return true;
  if (/^[-?:,[\]{}#&*!|>'"%@`]/.test(text)) return true;
  if (/^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$/.test(text)) return true;
  if (text !== text.trim()) return true;
  // ": " starts a mapping and " #" starts a comment.
  return text.includes(": ") || text.includes(" #") || text.endsWith(":");
}

function quote(text) {
  return `"${text.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function scalar(value) {
  if (value === null) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (typeof value !== "string") {
    throw new TypeError(`Unsupported YAML scalar type: ${typeof value}`);
  }
  return needsQuote(value) ? quote(value) : value;
}

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// Render a key/value pair into lines; indent is the current number of spaces.
function renderEntry(key, value, indent) {
  const pad = " ".repeat(indent);

  if (typeof value === "string" && value.includes("\n")) {
    const body = value.replace(/\n+$/, "").split("\n");
    return [`${pad}${key}: |`, ...body.map((line) => `${pad}  ${line}`.trimEnd())];
  }
  if (Array.isArray(value)) {
    if (value.length === 0) return [`${pad}${key}: []`];
    return [`${pad}${key}:`, ...renderSequence(value, indent)];
  }
  if (isPlainObject(value)) {
    if (Object.keys(value).length === 0) return [`${pad}${key}: {}`];
    return [`${pad}${key}:`, ...renderMap(value, indent + 2)];
  }
  return [`${pad}${key}: ${scalar(value)}`];
}

function renderSequence(items, indent) {
  const pad = " ".repeat(indent);
  const lines = [];
  for (const item of items) {
    if (isPlainObject(item)) {
      if (Object.keys(item).length === 0) {
        lines.push(`${pad}- {}`);
        continue;
      }
      const inner = renderMap(item, indent + 2);
      // Prefix the first line with "- " and keep subsequent lines aligned.
      lines.push(`${pad}- ${inner[0].slice(indent + 2)}`, ...inner.slice(1));
      continue;
    }
    if (Array.isArray(item)) {
      throw new TypeError("Nested arrays are unsupported; wrap the inner array in an object");
    }
    lines.push(`${pad}- ${scalar(item)}`);
  }
  return lines;
}

function renderMap(map, indent) {
  const lines = [];
  for (const [key, value] of Object.entries(map)) {
    if (value === undefined) continue;
    lines.push(...renderEntry(key, value, indent));
  }
  return lines;
}

export function toYaml(document) {
  return `${renderMap(document, 0).join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Design invariants fail hard and identify the ledger field that must change.
// ---------------------------------------------------------------------------

// Actions from official GitHub organizations may use tags; other actions require a 40-character SHA.
const TRUSTED_ACTION_OWNERS = new Set(["actions", "github"]);
const LOOSE_SECRET_REFERENCE = /\$\{\{secrets\./;
const BRACKET_SECRET_REFERENCE = /\$\{\{\s*secrets\s*\[/;

function checkActionRef(uses, where, errors) {
  const [owner] = uses.split("/");
  if (TRUSTED_ACTION_OWNERS.has(owner)) return;
  if (!/@[0-9a-f]{40}$/.test(uses)) {
    errors.push(`${where}: third-party action \`${uses}\` must pin a 40-character SHA to control supply-chain risk; use owner/repo@<sha>`);
  }
}

// check-secrets.mjs intentionally flags `${{secrets.X}}` (without spaces) and
// quoted references. Enforce the one compliant form here rather than weakening
// the scanner and its protection of real credentials.
function checkSecretStyle(text, where, errors) {
  if (LOOSE_SECRET_REFERENCE.test(text)) {
    errors.push(`${where}: secret references must use \${{ secrets.NAME }} with spaces inside the braces; other forms are flagged by this repository's secret scanner`);
  }
  for (const match of text.matchAll(/["']\$\{\{\s*secrets\./g)) {
    errors.push(`${where}: do not quote secret references (offset ${match.index}); quoted references are flagged by this repository's secret scanner`);
  }
  if (BRACKET_SECRET_REFERENCE.test(text)) {
    errors.push(`${where}: bracket notation is not allowed for secrets; use statically auditable \${{ secrets.NAME }}`);
  }
}

function collectSecretNames(text, into) {
  for (const expression of text.matchAll(/\$\{\{([\s\S]*?)\}\}/g)) {
    for (const match of expression[1].matchAll(
      /\bsecrets\.([A-Za-z_][A-Za-z0-9_]*)\b/g,
    )) {
      into.add(match[1]);
    }
  }
}

// ---------------------------------------------------------------------------
// Assembly: the ledger states what to do; this renderer adds the safe implementation.
// ---------------------------------------------------------------------------

// Deployment guard without ${{ }}, so it can be combined with a user-provided if
// expression in one block. Pull requests never publish; manual runs default to dry-run.
const DEPLOY_GUARD_EXPRESSION =
  "github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || !inputs.dry_run)";

// Strip `${{ expr }}` to `expr`, leaving a bare expression unchanged. Without
// this normalization, `${{ A }} && (B)` would be invalid workflow syntax.
function bareExpression(text) {
  const wrapped = /^\s*\$\{\{(.*)\}\}\s*$/s.exec(text);
  return (wrapped ? wrapped[1] : text).trim();
}

// env and with are nested objects and require recursive scanning. Otherwise a
// common violation such as `env: { X: "${{secrets.Y}}" }` would be missed.
function walkStrings(value, visit) {
  if (typeof value === "string") {
    visit(value);
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) walkStrings(item, visit);
    return;
  }
  if (isPlainObject(value)) {
    for (const item of Object.values(value)) walkStrings(item, visit);
  }
}

function normalizeStep(
  step,
  where,
  errors,
  secretNames,
  isDeploy,
  workflowState,
) {
  if (!isPlainObject(step)) {
    errors.push(`${where}: step must be an object`);
    return {};
  }
  if (
    Object.hasOwn(step, "continue-on-error") &&
    step["continue-on-error"] !== false
  ) {
    errors.push(
      `${where}: continue-on-error must be omitted or explicitly false; true and dynamic expressions can create false-green results`,
    );
  }
  walkStrings(step, (text) => {
    checkSecretStyle(text, where, errors);
    collectSecretNames(text, secretNames);
  });

  const normalized = {};
  if (step.name) normalized.name = step.name;
  if (step.id) normalized.id = step.id;

  const hasUses = typeof step.uses === "string" && step.uses.trim() !== "";
  const hasRun = typeof step.run === "string" && step.run.trim() !== "";
  if (hasUses === hasRun) {
    errors.push(`${where}: exactly one of uses or run must be declared`);
  }
  if (step.uses !== undefined && !hasUses) {
    errors.push(`${where}: uses must be a non-empty string`);
  }
  if (step.run !== undefined && !hasRun) {
    errors.push(`${where}: run must be a non-empty string`);
  }

  if (hasUses) {
    checkActionRef(step.uses, where, errors);
    normalized.uses = step.uses;
  }
  if (hasRun) {
    normalized.run = step.run;
    // Linux defaults to `bash -e` without pipefail, so `false | true` would pass silently.
    normalized.shell = step.shell ?? "bash";
  }
  const hasDeployClassification = Object.hasOwn(step, "deployStep");
  if (isDeploy && !hasDeployClassification) {
    errors.push(
      `${where}.deployStep: every step in a kind: deploy workflow must explicitly be true (real publication) or false (safe preparation/validation)`,
    );
  }
  if (!isDeploy && hasDeployClassification) {
    errors.push(
      `${where}.deployStep: deployStep is allowed only in a kind: deploy workflow`,
    );
  }
  if (
    hasDeployClassification &&
    typeof step.deployStep !== "boolean"
  ) {
    errors.push(`${where}.deployStep: must be a boolean`);
  }
  const guardAsDeploy =
    isDeploy &&
    (!hasDeployClassification || step.deployStep !== false);
  if (guardAsDeploy) {
    if (step.deployStep === true) workflowState.deployStepCount += 1;
    const guard = step.if
      ? `${DEPLOY_GUARD_EXPRESSION} && (${bareExpression(step.if)})`
      : DEPLOY_GUARD_EXPRESSION;
    normalized.if = `\${{ ${guard} }}`;
  } else if (step.if) {
    normalized.if = step.if;
  }
  if (step.with) normalized.with = step.with;
  if (step.env) normalized.env = step.env;
  return normalized;
}

function normalizeJob(
  job,
  where,
  errors,
  secretNames,
  isDeploy,
  workflowState,
) {
  if (!isPlainObject(job)) {
    errors.push(`${where}: job must be an object`);
    return { "runs-on": "ubuntu-latest", steps: [] };
  }
  const normalized = {};
  if (job.name) normalized.name = job.name;

  if (job.matrix) {
    normalized["runs-on"] = job.runsOn ?? "${{ matrix.os }}";
    normalized.strategy = { "fail-fast": false, matrix: job.matrix };
  } else {
    normalized["runs-on"] = job.runsOn ?? "ubuntu-latest";
  }

  if (job.needs) normalized.needs = job.needs;
  if (job.permissions) normalized.permissions = job.permissions;
  if (job.environment) normalized.environment = job.environment;
  if (job.env) {
    walkStrings(job.env, (text) => {
      checkSecretStyle(text, `${where}.env`, errors);
      collectSecretNames(text, secretNames);
    });
    normalized.env = job.env;
  }

  if (!Array.isArray(job.steps) || job.steps.length === 0) {
    errors.push(`${where}: job must contain at least one step`);
    normalized.steps = [];
    return normalized;
  }
  const stepIds = new Set();
  normalized.steps = job.steps.map((step, index) => {
    const stepWhere = `${where}.steps[${index}]`;
    if (isPlainObject(step) && step.id !== undefined) {
      if (
        typeof step.id !== "string" ||
        !/^[A-Za-z_][A-Za-z0-9_-]*$/.test(step.id)
      ) {
        errors.push(`${stepWhere}.id: must be a valid step id`);
      } else if (stepIds.has(step.id)) {
        errors.push(`${stepWhere}.id: \`${step.id}\` is duplicated within the same job`);
      } else {
        stepIds.add(step.id);
      }
    }
    return normalizeStep(
      step,
      stepWhere,
      errors,
      secretNames,
      isDeploy,
      workflowState,
    );
  });
  return normalized;
}

function buildTriggers(spec, isDeploy, errors, where) {
  const on = {};
  if (spec.pullRequest) on.pull_request = {};
  if (Array.isArray(spec.pushBranches) && spec.pushBranches.length > 0) {
    on.push = { branches: spec.pushBranches };
  }
  if (Array.isArray(spec.pushTags) && spec.pushTags.length > 0) {
    on.push = { ...(on.push ?? {}), tags: spec.pushTags };
  }
  if (spec.pullRequestTarget) {
    errors.push(`${where}: pull_request_target is forbidden because fork PR code can access repository secrets through this known credential-theft path`);
  }
  // Deploy workflows need a manual trigger so rerunning an older commit remains a rollback path.
  if (isDeploy || spec.workflowDispatch) {
    on.workflow_dispatch = isDeploy
      ? {
          inputs: {
            dry_run: {
              description: "Run a dry-run without publishing",
              type: "boolean",
              default: true,
              required: false,
            },
          },
        }
      : {};
  }
  if (Object.keys(on).length === 0) {
    errors.push(`${where}: the workflow has no trigger and will never run`);
  }
  return on;
}

export function renderWorkflow(spec, answersHash) {
  const errors = [];
  const secretNames = new Set();
  const where = `workflows[${spec.id ?? "?"}]`;
  const isDeploy = spec.kind === "deploy";
  const workflowState = { deployStepCount: 0 };

  const document = {
    name: spec.displayName ?? spec.id,
    on: buildTriggers(spec.on ?? {}, isDeploy, errors, where),
    // Once any permission is declared, undeclared permissions become none; this is the minimum set.
    permissions: spec.permissions ?? { contents: "read" },
    concurrency: {
      group: spec.concurrencyGroup ?? "${{ github.workflow }}-${{ github.ref }}",
      // A later run must not cancel deployment or release work and leave partial state.
      "cancel-in-progress": !isDeploy && spec.kind !== "release",
    },
    jobs: {},
  };

  if (!Array.isArray(spec.jobs) || spec.jobs.length === 0) {
    errors.push(`${where}: at least one job is required`);
  } else {
    const jobIds = new Set();
    for (const job of spec.jobs) {
      const jobId = job?.id;
      if (
        typeof jobId !== "string" ||
        !/^[A-Za-z_][A-Za-z0-9_-]*$/.test(jobId)
      ) {
        errors.push(`${where}: job id must start with a letter or underscore and contain only letters, digits, _, or -`);
        continue;
      }
      if (jobIds.has(jobId)) {
        errors.push(`${where}: job id \`${jobId}\` is duplicated`);
        continue;
      }
      jobIds.add(jobId);
      document.jobs[job.id] = normalizeJob(
        job,
        `${where}.jobs[${job.id}]`,
        errors,
        secretNames,
        isDeploy,
        workflowState,
      );
    }
  }
  if (isDeploy && workflowState.deployStepCount === 0) {
    errors.push(
      `${where}: kind: deploy requires at least one deployStep: true so the default dry_run blocks real publication`,
    );
  }

  const metadata = Object.entries(spec.managedMetadata ?? {}).map(
    ([key, value]) => `# ${key}: ${value}`,
  );
  const header = [
    MANAGED_MARKER,
    `# answers-hash: ${answersHash}`,
    ...metadata,
    "# Generated by npm run gen:cicd from docs/contracts/cicd-answers.json.",
    "# Do not edit this file directly. Update the ledger and regenerate it, or npm run quality will report drift.",
    "",
  ].join("\n");

  return { yaml: header + toYaml(document), errors, secretNames: [...secretNames].sort() };
}

export function readAnswers() {
  if (!existsSync(ANSWERS_PATH)) return null;
  return JSON.parse(readFileSync(ANSWERS_PATH, "utf8"));
}

export function answersHash(answers) {
  return createHash("sha256").update(JSON.stringify(answers)).digest("hex").slice(0, 16);
}

function contentHash(content) {
  return createHash("sha256").update(content).digest("hex");
}

function sameKeys(left, right) {
  const a = Object.keys(left).sort();
  const b = Object.keys(right).sort();
  return a.length === b.length && a.every((key, index) => key === b[index]);
}

function validateVersionSource(path, where, errors) {
  if (typeof path !== "string" || path.trim() === "") {
    errors.push(`${where}: version-source path must be a non-empty string`);
    return;
  }
  if (isAbsolute(path)) {
    errors.push(`${where}: version source must be a repository-relative path, not an absolute path`);
    return;
  }
  if (
    path.includes("\\") ||
    path.split("/").some((segment) => segment === "" || segment === "." || segment === "..")
  ) {
    errors.push(`${where}: version source must be a normalized repository-relative path`);
    return;
  }
  const target = resolve(ROOT, path);
  const fromRoot = relative(ROOT, target);
  if (fromRoot === ".." || fromRoot.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`)) {
    errors.push(`${where}: version source must not escape the repository`);
    return;
  }
  let stats;
  try {
    stats = lstatSync(target);
  } catch (error) {
    if (error.code !== "ENOENT") {
      errors.push(`${where}: could not inspect version-source file status: ${error.message}`);
      return;
    }
  }
  if (!stats || !stats.isFile()) {
    errors.push(`${where}: version-source file does not exist: ${path}`);
  } else if (stats.isSymbolicLink()) {
    errors.push(`${where}: version source must not be a symbolic link`);
  }
}

function validatePackagePath(path, errors) {
  if (typeof path !== "string" || path.trim() === "") {
    errors.push("releasePlease.config.packages package path must be a non-empty string");
    return;
  }
  if (
    path !== "." &&
    (isAbsolute(path) ||
      path.includes("\\") ||
      path.split("/").some((segment) => segment === "" || segment === "." || segment === ".."))
  ) {
    errors.push(`releasePlease.config.packages[${path}]: must be a normalized repository-relative directory`);
    return;
  }
  const target = resolve(ROOT, path);
  let stats;
  try {
    stats = lstatSync(target);
  } catch (error) {
    if (error.code !== "ENOENT") {
      errors.push(`releasePlease.config.packages[${path}]: could not inspect directory status: ${error.message}`);
      return;
    }
  }
  if (!stats || !stats.isDirectory()) {
    errors.push(`releasePlease.config.packages[${path}]: package directory does not exist`);
  } else if (stats.isSymbolicLink()) {
    errors.push(`releasePlease.config.packages[${path}]: package directory must not be a symbolic link`);
  }
}

function packageFilePath(packagePath, file, where, errors) {
  if (
    typeof file !== "string" ||
    file.trim() === "" ||
    isAbsolute(file) ||
    file.includes("\\") ||
    file.split("/").some((segment) => segment === "" || segment === "." || segment === "..")
  ) {
    errors.push(`${where}: must be a normalized relative file path within the package directory`);
    return null;
  }
  return packagePath === "." ? file : `${packagePath}/${file}`;
}

function effectivePackageOption(config, packageConfig, key) {
  return packageConfig[key] ?? config[key];
}

function validateExtraFilesDeclaration(value, where, errors) {
  if (!Array.isArray(value)) {
    errors.push(`${where} must be an array`);
    return;
  }

  const seenPaths = new Set();
  const supportedFields = new Set([
    "glob",
    "jsonpath",
    "path",
    "type",
    "xpath",
  ]);
  for (const [index, item] of value.entries()) {
    const itemWhere = `${where}[${index}]`;
    let path;
    if (typeof item === "string") {
      path = item;
    } else if (isPlainObject(item)) {
      for (const key of Object.keys(item)) {
        if (!supportedFields.has(key)) {
          errors.push(`${itemWhere}.${key}: this extra-files field is not supported in the current increment`);
        }
      }
      path = item.path;
      if (item.glob === true) {
        errors.push(
          `${itemWhere}: glob is not supported in the current increment; list explicit files so version sources remain auditable`,
        );
      } else if (item.glob !== undefined && typeof item.glob !== "boolean") {
        errors.push(`${itemWhere}.glob must be a boolean`);
      }
      const requiredSelector = {
        json: "jsonpath",
        toml: "jsonpath",
        yaml: "jsonpath",
        xml: "xpath",
      }[item.type];
      if (
        !["json", "toml", "yaml", "xml", "pom", "generic"].includes(item.type)
      ) {
        errors.push(`${itemWhere}.type is not a release-please-supported extra-files type`);
      } else if (
        requiredSelector &&
        (typeof item[requiredSelector] !== "string" ||
          item[requiredSelector].trim() === "")
      ) {
        errors.push(`${itemWhere}.${requiredSelector} must be a non-empty string`);
      }
    } else {
      errors.push(`${itemWhere}: must be a path string or an object with type/path`);
      continue;
    }

    const normalizedPath = packageFilePath(
      ".",
      path,
      `${itemWhere}.path`,
      errors,
    );
    if (normalizedPath) {
      if (seenPaths.has(normalizedPath)) {
        errors.push(`${itemWhere}: version file \`${normalizedPath}\` is duplicated`);
      }
      seenPaths.add(normalizedPath);
    }
  }
}

function validateDeclaredReleaseOptions(container, where, errors) {
  if (Object.hasOwn(container, "release-type")) {
    const releaseType = container["release-type"];
    if (typeof releaseType !== "string" || releaseType.trim() === "") {
      errors.push(`${where}.release-type must be a non-empty string`);
    } else if (!SUPPORTED_RELEASE_TYPES.has(releaseType)) {
      errors.push(
        `${where}.release-type: the current increment supports only node or simple, received \`${releaseType}\``,
      );
    }
  }

  if (Object.hasOwn(container, "skip-github-release")) {
    const skipGitHubRelease = container["skip-github-release"];
    if (typeof skipGitHubRelease !== "boolean") {
      errors.push(`${where}.skip-github-release must be a boolean`);
    } else if (skipGitHubRelease) {
      errors.push(`${where}: the current increment does not allow skip-github-release: true`);
    }
  }

  if (Object.hasOwn(container, "version-file")) {
    const versionFile = container["version-file"];
    if (typeof versionFile !== "string" || versionFile.trim() === "") {
      errors.push(`${where}.version-file must be a non-empty string`);
    } else {
      packageFilePath(
        ".",
        versionFile,
        `${where}.version-file`,
        errors,
      );
    }
  }

  if (Object.hasOwn(container, "extra-files")) {
    validateExtraFilesDeclaration(
      container["extra-files"],
      `${where}.extra-files`,
      errors,
    );
  }
}

function validateExtraFiles(config, packageConfig, packagePath, errors) {
  const value = effectivePackageOption(config, packageConfig, "extra-files");
  if (value === undefined) return [];
  if (!Array.isArray(value)) {
    errors.push(`releasePlease.config.packages[${packagePath}].extra-files must be an array`);
    return [];
  }

  const paths = [];
  const seenPaths = new Set();
  for (const [index, item] of value.entries()) {
    const where = `releasePlease.config.packages[${packagePath}].extra-files[${index}]`;
    let path;
    if (typeof item === "string") {
      path = item;
    } else if (isPlainObject(item)) {
      path = item.path;
      if (item.glob === true) {
        errors.push(`${where}: glob is not supported in the current increment; list explicit files so version sources remain auditable`);
      } else if (item.glob !== undefined && typeof item.glob !== "boolean") {
        errors.push(`${where}.glob must be a boolean`);
      }
      const requiredSelector = {
        json: "jsonpath",
        toml: "jsonpath",
        yaml: "jsonpath",
        xml: "xpath",
      }[item.type];
      if (
        !["json", "toml", "yaml", "xml", "pom", "generic"].includes(item.type)
      ) {
        errors.push(`${where}.type is not a release-please-supported extra-files type`);
      } else if (
        requiredSelector &&
        (typeof item[requiredSelector] !== "string" ||
          item[requiredSelector].trim() === "")
      ) {
        errors.push(`${where}.${requiredSelector} must be a non-empty string`);
      }
    } else {
      errors.push(`${where}: must be a path string or an object with type/path`);
      continue;
    }

    const repositoryPath = packageFilePath(packagePath, path, `${where}.path`, errors);
    if (repositoryPath) {
      if (seenPaths.has(repositoryPath)) {
        errors.push(`${where}: version file \`${repositoryPath}\` is duplicated`);
      } else {
        seenPaths.add(repositoryPath);
        paths.push({ path: repositoryPath, item });
      }
    }
  }
  return paths;
}

function validateVersionMapping(
  config,
  packages,
  versionSources,
  errors,
) {
  const mapping = {
    primaryVersionSources: {},
    releaseTypes: {},
  };
  if (!packages || !isPlainObject(versionSources)) {
    return mapping;
  }

  for (const [packagePath, packageConfig] of Object.entries(packages)) {
    if (!isPlainObject(packageConfig)) continue;
    const releaseType =
      packageConfig["release-type"] ?? config["release-type"];
    if (!SUPPORTED_RELEASE_TYPES.has(releaseType)) continue;
    mapping.releaseTypes[packagePath] = releaseType;

    let primaryPath;
    if (releaseType === "node") {
      primaryPath = packageFilePath(
        packagePath,
        "package.json",
        `releasePlease.config.packages[${packagePath}]`,
        errors,
      );
    } else {
      const versionFile = effectivePackageOption(
        config,
        packageConfig,
        "version-file",
      ) ?? "version.txt";
      primaryPath = packageFilePath(
        packagePath,
        versionFile,
        `releasePlease.config.packages[${packagePath}].version-file`,
        errors,
      );
    }

    const extras = validateExtraFiles(
      config,
      packageConfig,
      packagePath,
      errors,
    );
    const mappedPaths = new Set(
      [primaryPath, ...extras.map((extra) => extra.path)].filter(Boolean),
    );
    if (primaryPath) mapping.primaryVersionSources[packagePath] = primaryPath;
    const declaredPaths = new Set(
      Array.isArray(versionSources[packagePath])
        ? versionSources[packagePath]
        : [],
    );
    for (const path of mappedPaths) {
      if (!declaredPaths.has(path)) {
        errors.push(
          `releasePlease.versionSources[${packagePath}]: missing version file \`${path}\` that release-please will update`,
        );
      }
    }
    for (const path of declaredPaths) {
      if (!mappedPaths.has(path)) {
        errors.push(
          `releasePlease.versionSources[${packagePath}]: \`${path}\` is not mapped to the ${releaseType} primary version file or extra-files`,
        );
      }
    }

    for (const extra of extras) {
      if (
        (typeof extra.item === "string" || extra.item.type === "generic") &&
        lstatIfPresent(resolve(ROOT, extra.path))?.isFile() &&
        !/x-release-please-(?:major|minor|patch|version|date)/.test(
          readFileSync(resolve(ROOT, extra.path), "utf8"),
        )
      ) {
        errors.push(
          `releasePlease.config.packages[${packagePath}].extra-files: \`${extra.path}\` uses the generic updater without an x-release-please-* annotation`,
        );
      }
    }
  }
  return mapping;
}

function isValidBranchName(value) {
  if (typeof value !== "string" || value.trim() === "") return false;
  if (
    value === "@" ||
    value === "HEAD" ||
    value.startsWith("-") ||
    value.startsWith("/") ||
    value.endsWith("/") ||
    value.endsWith(".") ||
    value.includes("..") ||
    value.includes("@{") ||
    /[\x00-\x20\x7f~^:?*[\]\\]/.test(value)
  ) {
    return false;
  }
  return !value.split("/").some(
    (component) =>
      component === "" ||
      component.startsWith(".") ||
      component.endsWith(".lock"),
  );
}

function isPortableWorkflowFileName(value) {
  if (typeof value !== "string" || !/^[\w.-]+\.ya?ml$/.test(value)) {
    return false;
  }
  const stem = value.slice(0, value.lastIndexOf(".")).toUpperCase();
  return !/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/.test(stem);
}

function validateReleaseTitlePattern(value, key, requiredPlaceholder, errors) {
  if (
    typeof value !== "string" ||
    !/^chore(?:\$\{scope\}|\([A-Za-z0-9._/${}-]+\)): [\x20-\x7e]*[A-Za-z][\x20-\x7e]*$/.test(value) ||
    !value.includes(requiredPlaceholder)
  ) {
    errors.push(
      `releasePlease.config.${key}: must use an English commit subject and include ${requiredPlaceholder}`,
    );
  }
}

// The release-please manifest is runtime state. Validate its structure without
// comparing bytes to initialManifest: merged Release PRs advance versions, and
// regeneration must never reset them to bootstrap values.
export function validateReleasePleaseManifest(releasePlease, manifest) {
  const errors = [];
  const expectedPackages = releasePlease?.packageKeys ?? [];

  if (!isPlainObject(manifest)) {
    return [`${RELEASE_PLEASE_MANIFEST_NAME}: must be a JSON object`];
  }
  if (!sameKeys(Object.fromEntries(expectedPackages.map((key) => [key, true])), manifest)) {
    errors.push(
      `${RELEASE_PLEASE_MANIFEST_NAME}: package paths must exactly match packages in release-please-config.json`,
    );
  }
  for (const [path, version] of Object.entries(manifest)) {
    if (typeof version !== "string" || !SEMVER.test(version)) {
      errors.push(`${RELEASE_PLEASE_MANIFEST_NAME}: version for \`${path}\` must be valid SemVer, received \`${version}\``);
    }
  }
  return errors;
}

// versionSources is an audit inventory and the manifest is Release Please runtime
// state. Compare their current values. initialManifest is used only for bootstrap;
// later runs must pass the current manifest advanced by Release PRs.
export function validateReleasePleaseVersionSources(releasePlease, manifest) {
  const errors = [];
  for (const packagePath of releasePlease?.packageKeys ?? []) {
    const source = releasePlease.primaryVersionSources?.[packagePath];
    const releaseType = releasePlease.releaseTypes?.[packagePath];
    if (!source || !releaseType) continue;

    let sourceVersion;
    try {
      if (releaseType === "node") {
        sourceVersion = JSON.parse(readFileSync(resolve(ROOT, source), "utf8")).version;
      } else {
        sourceVersion = readFileSync(resolve(ROOT, source), "utf8").trim();
      }
    } catch (error) {
      errors.push(
        `releasePlease.versionSources[${packagePath}]: could not read primary version file \`${source}\`: ${error.message}`,
      );
      continue;
    }
    if (typeof sourceVersion !== "string" || !SEMVER.test(sourceVersion)) {
      errors.push(
        `releasePlease.versionSources[${packagePath}]: value \`${sourceVersion}\` in primary version file \`${source}\` is not valid SemVer`,
      );
    } else if (sourceVersion !== manifest?.[packagePath]) {
      errors.push(
        `releasePlease.versionSources[${packagePath}]: primary version file \`${source}\` is \`${sourceVersion}\`, which does not match manifest value \`${manifest?.[packagePath]}\``,
      );
    }
  }
  return errors;
}

function buildReleasePlease(spec, answersHash) {
  if (spec === undefined) return { releasePlease: null, errors: [] };

  const errors = [];
  if (!isPlainObject(spec)) {
    return { releasePlease: null, errors: ["releasePlease must be an object"] };
  }

  const workflowFile = spec.workflowFile;
  if (!isPortableWorkflowFileName(workflowFile)) {
    errors.push("releasePlease.workflowFile must be a cross-platform-safe filename such as release-please.yml");
  }

  const targetBranch = spec.targetBranch;
  if (!isValidBranchName(targetBranch)) {
    errors.push("releasePlease.targetBranch must be an explicit, valid Git branch name");
  }

  const credential = spec.credential;
  let tokenReference;
  if (!isPlainObject(credential)) {
    errors.push("releasePlease.credential must explicitly declare mode");
  } else if (credential.mode === "github-token") {
    if (credential.secretName !== undefined) {
      errors.push("releasePlease.credential must not set secretName when mode is github-token");
    }
  } else if (credential.mode === "secret") {
    if (
      typeof credential.secretName !== "string" ||
      !/^[A-Za-z_][A-Za-z0-9_]*$/.test(credential.secretName)
    ) {
      errors.push("releasePlease.credential.secretName must be a valid GitHub Actions secret name");
    } else {
      tokenReference = `\${{ secrets.${credential.secretName} }}`;
    }
  } else {
    errors.push("releasePlease.credential.mode must be github-token or secret");
  }

  const config = spec.config;
  const packages = isPlainObject(config) && isPlainObject(config.packages) ? config.packages : null;
  if (isPlainObject(config)) {
    validateDeclaredReleaseOptions(
      config,
      "releasePlease.config",
      errors,
    );
    for (const key of Object.keys(config)) {
      if (key === "skip-github-pull-request") continue;
      if (!RELEASE_CONFIG_FIELDS.has(key)) {
        errors.push(
          `releasePlease.config.${key}: this release-please field is unsupported in the current increment and cannot pass through without validation`,
        );
      }
    }
    if (
      config.$schema !== undefined &&
      (typeof config.$schema !== "string" || config.$schema.trim() === "")
    ) {
      errors.push("releasePlease.config.$schema must be a non-empty string");
    }
    if (Object.hasOwn(config, "skip-github-pull-request")) {
      errors.push(
        "releasePlease.config.skip-github-pull-request is not a manifest config field, and the current increment does not allow skipping the Release PR",
      );
    }
  }
  if (!packages || Object.keys(packages).length === 0) {
    errors.push("releasePlease.config.packages must be a non-empty object");
  } else {
    for (const [path, packageConfig] of Object.entries(packages)) {
      validatePackagePath(path, errors);
      if (!isPlainObject(packageConfig)) {
        errors.push(`releasePlease.config.packages[${path}]: must be an object`);
        continue;
      }
      validateDeclaredReleaseOptions(
        packageConfig,
        `releasePlease.config.packages[${path}]`,
        errors,
      );
      for (const key of Object.keys(packageConfig)) {
        if (key === "skip-github-pull-request") continue;
        if (!RELEASE_PACKAGE_FIELDS.has(key)) {
          errors.push(
            `releasePlease.config.packages[${path}].${key}: this package field is unsupported in the current increment and cannot pass through without validation`,
          );
        }
      }
      const releaseType = packageConfig["release-type"] ?? config["release-type"];
      if (typeof releaseType !== "string" || releaseType.trim() === "") {
        errors.push(`releasePlease.config.packages[${path}]: must explicitly declare release-type`);
      } else if (!SUPPORTED_RELEASE_TYPES.has(releaseType)) {
        errors.push(
          `releasePlease.config.packages[${path}]: the current increment supports only node or simple, received \`${releaseType}\``,
        );
      }
      if (
        Object.hasOwn(packageConfig, "skip-github-pull-request")
      ) {
        errors.push(
          `releasePlease.config.packages[${path}]: skip-github-pull-request is not a manifest config field, and the current increment does not allow skipping the Release PR`,
        );
      }
      const skipGitHubRelease = effectivePackageOption(
        config,
        packageConfig,
        "skip-github-release",
      );
      if (
        skipGitHubRelease !== undefined &&
        typeof skipGitHubRelease !== "boolean"
      ) {
        errors.push(
          `releasePlease.config.packages[${path}].skip-github-release must be a boolean`,
        );
      } else if (skipGitHubRelease === true) {
        errors.push(
          `releasePlease.config.packages[${path}]: the current increment does not allow skip-github-release: true`,
        );
      }
    }
  }
  for (const key of ["include-v-in-tag", "include-component-in-tag"]) {
    if (typeof config?.[key] !== "boolean") {
      errors.push(`releasePlease.config.${key} must explicitly be true or false; tag rules cannot be inferred`);
    }
  }
  if (
    config?.["bootstrap-sha"] !== undefined &&
    (typeof config["bootstrap-sha"] !== "string" ||
      !/^[0-9a-f]{40}$/.test(config["bootstrap-sha"]))
  ) {
    errors.push("releasePlease.config.bootstrap-sha must be a complete 40-character lowercase commit SHA");
  }

  const pullRequestTitlePattern =
    config?.["pull-request-title-pattern"] ??
    "chore${scope}: release${component} ${version}";
  const groupPullRequestTitlePattern =
    config?.["group-pull-request-title-pattern"] ??
    "chore(${branch}): release ${branch}";
  validateReleaseTitlePattern(
    pullRequestTitlePattern,
    "pull-request-title-pattern",
    "${version}",
    errors,
  );
  validateReleaseTitlePattern(
    groupPullRequestTitlePattern,
    "group-pull-request-title-pattern",
    "${branch}",
    errors,
  );

  const initialManifest = spec.initialManifest;
  if (!isPlainObject(initialManifest) || Object.keys(initialManifest).length === 0) {
    errors.push("releasePlease.initialManifest must be a non-empty object");
  }

  const versionSources = spec.versionSources;
  if (!isPlainObject(versionSources) || Object.keys(versionSources).length === 0) {
    errors.push("releasePlease.versionSources must register at least one project version source per package path");
  }

  if (packages && isPlainObject(initialManifest) && !sameKeys(packages, initialManifest)) {
    errors.push("releasePlease.initialManifest package paths must exactly match config.packages");
  }
  if (packages && isPlainObject(versionSources) && !sameKeys(packages, versionSources)) {
    errors.push("releasePlease.versionSources package paths must exactly match config.packages");
  }

  if (isPlainObject(initialManifest)) {
    for (const [path, version] of Object.entries(initialManifest)) {
      if (typeof version !== "string" || !SEMVER.test(version)) {
        errors.push(`releasePlease.initialManifest[${path}]: must be valid SemVer`);
      }
    }
  }

  if (isPlainObject(versionSources)) {
    const sourceOwners = new Map();
    for (const [path, sources] of Object.entries(versionSources)) {
      if (!Array.isArray(sources) || sources.length === 0) {
        errors.push(`releasePlease.versionSources[${path}]: must be a non-empty path array`);
        continue;
      }
      const packageSources = new Set();
      for (const [index, source] of sources.entries()) {
        validateVersionSource(source, `releasePlease.versionSources[${path}][${index}]`, errors);
        if (packageSources.has(source)) {
          errors.push(
            `releasePlease.versionSources[${path}]: version source \`${source}\` is registered more than once`,
          );
        } else {
          packageSources.add(source);
        }
        if (sourceOwners.has(source) && sourceOwners.get(source) !== path) {
          errors.push(
            `releasePlease.versionSources: \`${source}\` belongs to both package \`${sourceOwners.get(source)}\` and \`${path}\`, creating two writers`,
          );
        } else {
          sourceOwners.set(source, path);
        }
      }
    }
  }

  const versionMapping = validateVersionMapping(
    config,
    packages,
    versionSources,
    errors,
  );

  if (errors.length > 0) return { releasePlease: null, errors };

  const normalizedConfig = {
    ...config,
    "pull-request-title-pattern": pullRequestTitlePattern,
    "group-pull-request-title-pattern": groupPullRequestTitlePattern,
  };
  const configJson = `${JSON.stringify(normalizedConfig, null, 2)}\n`;
  const withInputs = {
    "config-file": RELEASE_PLEASE_CONFIG_NAME,
    "manifest-file": RELEASE_PLEASE_MANIFEST_NAME,
    "target-branch": targetBranch,
    ...(tokenReference ? { ["token"]: tokenReference } : {}),
  };

  const workflowSpec = {
    id: "release-please",
    file: workflowFile,
    kind: "release",
    displayName: "Release Please",
    on: { pushBranches: [targetBranch] },
    permissions: {
      contents: "write",
      issues: "write",
      "pull-requests": "write",
    },
    concurrencyGroup: "release-please-${{ github.ref }}",
    managedMetadata: {
      [MANAGED_CONFIG_DIGEST]: contentHash(configJson),
    },
    jobs: [
      {
        id: "release-please",
        name: "Release Please",
        runsOn: "ubuntu-latest",
        steps: [
          {
            name: "Create or update release",
            id: "release",
            uses: RELEASE_PLEASE_ACTION,
            with: withInputs,
          },
        ],
      },
    ],
  };
  const rendered = renderWorkflow(workflowSpec, answersHash);

  return {
    releasePlease: {
      workflowFile,
      workflowYaml: rendered.yaml,
      configJson,
      initialManifestJson: `${JSON.stringify(initialManifest, null, 2)}\n`,
      packageKeys: Object.keys(packages).sort(),
      versionSources,
      primaryVersionSources: versionMapping.primaryVersionSources,
      releaseTypes: versionMapping.releaseTypes,
    },
    errors: rendered.errors,
    secretNames: rendered.secretNames,
  };
}

// Render all workflows and return { file -> yaml } plus validation errors for reuse by generation and checks.
export function renderAll(answers) {
  const files = new Map();
  const errors = [];
  const secretNames = new Set();
  const workflowSpecs = [];
  const normalizedWorkflowFiles = new Set();

  if (!isPlainObject(answers)) {
    return {
      files,
      errors: ["Decision-ledger root must be a JSON object"],
      secretNames: [],
      releasePlease: null,
    };
  }

  const hash = answersHash(answers);

  if (answers.workflows !== undefined && !Array.isArray(answers.workflows)) {
    errors.push("Decision-ledger workflows must be an array");
  } else if (Array.isArray(answers.workflows)) {
    workflowSpecs.push(...answers.workflows);
  }

  const release = buildReleasePlease(answers.releasePlease, hash);
  errors.push(...release.errors);
  if (release.releasePlease) {
    workflowSpecs.push({
      id: "release-please",
      file: release.releasePlease.workflowFile,
      __renderedYaml: release.releasePlease.workflowYaml,
    });
    for (const name of release.secretNames ?? []) secretNames.add(name);
  }

  if (workflowSpecs.length === 0 && answers.releasePlease === undefined) {
    errors.push("The decision ledger declares no workflow: workflows is empty and releasePlease is disabled");
  }

  for (const spec of workflowSpecs) {
    if (!isPlainObject(spec)) {
      errors.push("Every workflows entry must be an object");
      continue;
    }
    if (!isPortableWorkflowFileName(spec.file)) {
      errors.push(`workflows[${spec.id ?? "?"}]: file must be a cross-platform-safe filename such as build.yml`);
      continue;
    }
    const normalizedFile = spec.file.toLowerCase();
    if (normalizedWorkflowFiles.has(normalizedFile)) {
      errors.push(`workflows[${spec.id ?? "?"}]: file \`${spec.file}\` duplicates another workflow`);
      continue;
    }
    normalizedWorkflowFiles.add(normalizedFile);
    const rendered = spec.__renderedYaml
      ? { yaml: spec.__renderedYaml, errors: [], secretNames: [] }
      : renderWorkflow(spec, hash);
    errors.push(...rendered.errors);
    for (const name of rendered.secretNames) secretNames.add(name);
    files.set(spec.file, rendered.yaml);
  }
  return {
    files,
    errors,
    secretNames: [...secretNames].sort(),
    releasePlease: release.releasePlease,
  };
}

function lstatIfPresent(path) {
  try {
    return lstatSync(path);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

function inspectRegularFile(path, shown, errors) {
  let stats;
  try {
    stats = lstatIfPresent(path);
  } catch (error) {
    errors.push(`${shown}: could not inspect file status: ${error.message}`);
    return { exists: true, invalid: true };
  }
  if (stats === null) return { exists: false, content: null };
  if (stats.isSymbolicLink()) {
    errors.push(`${shown}: symbolic link rejected; the generator must not follow links outside the repository`);
    return { exists: true, invalid: true };
  }
  if (!stats.isFile()) {
    errors.push(`${shown}: exists but is not a regular file`);
    return { exists: true, invalid: true };
  }
  try {
    return { exists: true, content: readFileSync(path, "utf8") };
  } catch (error) {
    errors.push(`${shown}: could not read file: ${error.message}`);
    return { exists: true, invalid: true };
  }
}

function inspectWorkflowDirectories(errors) {
  for (const [path, shown] of [
    [resolve(ROOT, ".github"), ".github"],
    [WORKFLOW_DIRECTORY, ".github/workflows"],
  ]) {
    const stats = lstatIfPresent(path);
    if (stats === null) continue;
    if (stats.isSymbolicLink()) {
      errors.push(`${shown}: symbolic-link directory rejected; the generator must not follow links outside the repository`);
    } else if (!stats.isDirectory()) {
      errors.push(`${shown}: exists but is not a directory`);
    }
  }
}

function managedConfigDigestFromWorkflow(content) {
  const match = new RegExp(
    `^# ${MANAGED_CONFIG_DIGEST}: ([0-9a-f]{64})$`,
    "m",
  ).exec(content ?? "");
  return match?.[1] ?? null;
}

function prepareWritePlan(rendered) {
  const errors = [...rendered.errors];
  const artifacts = [];
  const workflowSnapshots = new Map();
  inspectWorkflowDirectories(errors);

  const desiredWorkflowNames = new Set(rendered.files.keys());
  const existingWorkflowNames = new Map();
  const workflowDirectoryStats = lstatIfPresent(WORKFLOW_DIRECTORY);
  if (workflowDirectoryStats?.isDirectory()) {
    for (const entry of readdirSync(WORKFLOW_DIRECTORY, {
      withFileTypes: true,
    })) {
      if (![".yml", ".yaml"].includes(extname(entry.name))) continue;
      const normalizedName = entry.name.toLowerCase();
      if (
        existingWorkflowNames.has(normalizedName) &&
        existingWorkflowNames.get(normalizedName) !== entry.name
      ) {
        errors.push(
          `.github/workflows: \`${existingWorkflowNames.get(normalizedName)}\` and \`${entry.name}\` differ only by case and would conflict in cross-platform checkouts`,
        );
      } else {
        existingWorkflowNames.set(normalizedName, entry.name);
      }
      const path = resolve(WORKFLOW_DIRECTORY, entry.name);
      const snapshot = inspectRegularFile(
        path,
        `.github/workflows/${entry.name}`,
        errors,
      );
      if (
        !snapshot.invalid &&
        snapshot.exists &&
        snapshot.content.startsWith(`${MANAGED_MARKER}\n`) &&
        !desiredWorkflowNames.has(entry.name)
      ) {
        errors.push(
          `.github/workflows/${entry.name}: remains generator-managed but is no longer declared in the ledger; obtain user confirmation before deleting it or restore the ledger entry so obsolete CI/CD cannot keep running`,
        );
      }
    }
  }

  for (const [file, content] of rendered.files) {
    const path = resolve(WORKFLOW_DIRECTORY, file);
    const shown = `.github/workflows/${file}`;
    const snapshot = inspectRegularFile(path, shown, errors);
    const existingCaseVariant = existingWorkflowNames.get(file.toLowerCase());
    if (existingCaseVariant && existingCaseVariant !== file) {
      errors.push(
        `${shown}: differs from existing .github/workflows/${existingCaseVariant} only by case; refusing to create a cross-platform conflict`,
      );
    }
    workflowSnapshots.set(file, snapshot);
    if (
      snapshot.exists &&
      !snapshot.invalid &&
      !snapshot.content.startsWith(`${MANAGED_MARKER}\n`)
    ) {
      errors.push(
        `${shown}: already exists and is not owned by this renderer; choose another workflowFile/file or perform an explicit user-approved migration`,
      );
    } else if (!snapshot.invalid && snapshot.content !== content) {
      artifacts.push({ path, shown, content, snapshot });
    }
  }

  const configSnapshot = inspectRegularFile(
    RELEASE_PLEASE_CONFIG_PATH,
    RELEASE_PLEASE_CONFIG_NAME,
    errors,
  );
  const manifestSnapshot = inspectRegularFile(
    RELEASE_PLEASE_MANIFEST_PATH,
    RELEASE_PLEASE_MANIFEST_NAME,
    errors,
  );

  if (rendered.releasePlease) {
    const releaseWorkflowSnapshot = workflowSnapshots.get(
      rendered.releasePlease.workflowFile,
    );
    if (
      configSnapshot.exists &&
      !configSnapshot.invalid &&
      configSnapshot.content !== rendered.releasePlease.configJson
    ) {
      const recordedDigest = managedConfigDigestFromWorkflow(
        releaseWorkflowSnapshot?.content,
      );
      if (
        recordedDigest === null ||
        recordedDigest !== contentHash(configSnapshot.content)
      ) {
        errors.push(
          `${RELEASE_PLEASE_CONFIG_NAME}: the managed release workflow digest cannot prove ownership of the existing content; refusing to overwrite it until it is backed up and the user approves migration`,
        );
      }
    }

    let manifest;
    if (manifestSnapshot.exists && !manifestSnapshot.invalid) {
      try {
        manifest = JSON.parse(manifestSnapshot.content);
        errors.push(
          ...validateReleasePleaseManifest(rendered.releasePlease, manifest),
          ...validateReleasePleaseVersionSources(
            rendered.releasePlease,
            manifest,
          ),
        );
      } catch (error) {
        errors.push(
          `${RELEASE_PLEASE_MANIFEST_NAME}: failed to parse JSON: ${error.message}`,
        );
      }
    } else if (!manifestSnapshot.invalid) {
      manifest = JSON.parse(rendered.releasePlease.initialManifestJson);
      errors.push(
        ...validateReleasePleaseVersionSources(
          rendered.releasePlease,
          manifest,
        ),
      );
      if (configSnapshot.exists || releaseWorkflowSnapshot?.exists) {
        errors.push(
          `${RELEASE_PLEASE_MANIFEST_NAME}: config or a managed release workflow exists but the manifest is missing, indicating lost runtime state; restore it from Git or a Release PR instead of rebuilding it from initialManifest`,
        );
      } else {
        artifacts.push({
          path: RELEASE_PLEASE_MANIFEST_PATH,
          shown: RELEASE_PLEASE_MANIFEST_NAME,
          content: rendered.releasePlease.initialManifestJson,
          snapshot: manifestSnapshot,
        });
      }
    }

    if (
      !configSnapshot.invalid &&
      configSnapshot.content !== rendered.releasePlease.configJson
    ) {
      artifacts.push({
        path: RELEASE_PLEASE_CONFIG_PATH,
        shown: RELEASE_PLEASE_CONFIG_NAME,
        content: rendered.releasePlease.configJson,
        snapshot: configSnapshot,
      });
    }
  } else {
    for (const [shown, snapshot] of [
      [RELEASE_PLEASE_CONFIG_NAME, configSnapshot],
      [RELEASE_PLEASE_MANIFEST_NAME, manifestSnapshot],
    ]) {
      if (snapshot.exists) {
        errors.push(
          `${shown}: the ledger disabled releasePlease but an old artifact remains; obtain user confirmation before deleting it or restore the ledger so obsolete releases cannot keep triggering`,
        );
      }
    }
  }

  return { artifacts, errors };
}

function verifySnapshot(artifact) {
  const current = lstatIfPresent(artifact.path);
  if (!artifact.snapshot.exists) {
    if (current !== null) {
      throw new Error(`${artifact.shown}: appeared after preflight; refusing to overwrite it`);
    }
    return;
  }
  if (
    current === null ||
    current.isSymbolicLink() ||
    !current.isFile() ||
    readFileSync(artifact.path, "utf8") !== artifact.snapshot.content
  ) {
    throw new Error(`${artifact.shown}: changed after preflight; refusing to continue writing`);
  }
}

export function writeTransaction(
  artifacts,
  { rename = renameSync } = {},
) {
  if (artifacts.length === 0) return [];
  if (artifacts.some((artifact) => dirname(artifact.path) === WORKFLOW_DIRECTORY)) {
    mkdirSync(WORKFLOW_DIRECTORY, { recursive: true });
  }

  const staged = [];
  const applied = [];
  try {
    for (const [index, artifact] of artifacts.entries()) {
      const temporaryPath = resolve(
        dirname(artifact.path),
        `.${basename(artifact.path)}.cicd-stage-${process.pid}-${index}-${randomUUID()}`,
      );
      writeFileSync(temporaryPath, artifact.content, {
        encoding: "utf8",
        flag: "wx",
      });
      staged.push({ ...artifact, temporaryPath, backupPath: null });
    }

    for (const item of staged) {
      verifySnapshot(item);
      item.installed = false;
      applied.push(item);
      if (item.snapshot.exists) {
        item.backupPath = resolve(
          dirname(item.path),
          `.${basename(item.path)}.cicd-backup-${process.pid}-${randomUUID()}`,
        );
        rename(item.path, item.backupPath);
      }
      rename(item.temporaryPath, item.path);
      item.installed = true;
    }
  } catch (error) {
    const rollbackErrors = [];
    for (const item of applied.reverse()) {
      try {
        if (item.installed && lstatIfPresent(item.path)) unlinkSync(item.path);
        if (item.backupPath && lstatIfPresent(item.backupPath)) {
          rename(item.backupPath, item.path);
          item.backupPath = null;
        }
      } catch (rollbackError) {
        rollbackErrors.push(`${item.shown}: ${rollbackError.message}`);
      }
    }
    for (const item of staged) {
      try {
        if (lstatIfPresent(item.temporaryPath)) unlinkSync(item.temporaryPath);
      } catch (cleanupError) {
        rollbackErrors.push(`${item.shown} temporary file: ${cleanupError.message}`);
      }
    }
    const suffix =
      rollbackErrors.length > 0
        ? `; rollback also encountered: ${rollbackErrors.join("; ")}`
        : "";
    throw new Error(`Transactional artifact write failed: ${error.message}${suffix}`);
  }

  const cleanupWarnings = [];
  for (const item of applied) {
    if (item.backupPath && lstatIfPresent(item.backupPath)) {
      try {
        unlinkSync(item.backupPath);
      } catch (error) {
        cleanupWarnings.push(
          `${item.shown}: the new artifact is active, but cleanup of the old-file backup failed; it remains at ${item.backupPath}: ${error.message}`,
        );
      }
    }
  }
  return cleanupWarnings;
}

function main() {
  const answers = readAnswers();
  if (answers === null) {
    process.stdout.write(`${relative(ROOT, ANSWERS_PATH)} was not found; generation skipped.\nRun npm run cicd:probe and complete the decisions first.\n`);
    return 0;
  }

  const rendered = renderAll(answers);
  const { files, secretNames, releasePlease } = rendered;
  const { artifacts, errors } = prepareWritePlan(rendered);
  const initializedManifest = artifacts.some(
    (artifact) => artifact.path === RELEASE_PLEASE_MANIFEST_PATH,
  );

  if (errors.length > 0) {
    process.stderr.write(
      `The decision ledger violates design invariants; no files were written:\n${errors
        .map((error) => `- ${error}`)
        .join("\n")}\n`,
    );
    return 1;
  }

  let cleanupWarnings;
  try {
    cleanupWarnings = writeTransaction(artifacts);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    return 1;
  }
  for (const warning of cleanupWarnings) {
    process.stderr.write(`Warning: ${warning}\n`);
  }

  for (const file of files.keys()) {
    process.stdout.write(`Reconciled .github/workflows/${file}\n`);
  }
  if (releasePlease) {
    process.stdout.write(`Reconciled ${RELEASE_PLEASE_CONFIG_NAME}\n`);
    if (initializedManifest) {
      process.stdout.write(`Initialized ${RELEASE_PLEASE_MANIFEST_NAME}\n`);
    } else if (lstatIfPresent(RELEASE_PLEASE_MANIFEST_PATH)) {
      process.stdout.write(`Preserved existing ${RELEASE_PLEASE_MANIFEST_NAME} as Release PR runtime state; it was not overwritten\n`);
    }
  }
  if (secretNames.length > 0) {
    process.stdout.write(`\nReferenced secrets (confirm they are configured remotely): ${secretNames.join(", ")}\n`);
  }
  return 0;
}

// Write files only when executed directly; check-cicd.mjs imports the pure functions above.
if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  process.exitCode = main();
}
