# Restart the remote preview host over SSH, normally from the Windows machine that
# initiated synchronization. preview.sh already owns fetch, detached checkout, and
# restart behavior; this script only triggers it remotely. Configuration precedence:
# command-line arguments, then scripts/dev/dev-workflow.env generated by scripts/init.mjs.
param(
    [string]$Branch,
    [string]$PreviewHost,
    [string]$RemoteRepoPath,
    [string]$RemoteUser,
    [string]$SshKeyName
)
$ErrorActionPreference = "Stop"

$envFile = Join-Path $PSScriptRoot "dev-workflow.env"
$envValues = @{}
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        # Trim trailing whitespace with a non-greedy match and remove paired outer
        # quotes to match preview.sh `source` semantics. This keeps manual quoting
        # or trailing spaces from corrupting hostnames or paths only on Windows.
        if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$') {
            $val = $matches[2]
            if ($val -match '^"(.*)"$' -or $val -match "^'(.*)'$") { $val = $matches[1] }
            $envValues[$matches[1]] = $val
        }
    }
}

if (-not $PreviewHost) { $PreviewHost = $envValues["PREVIEW_HOST"] }
if (-not $RemoteRepoPath) { $RemoteRepoPath = $envValues["REMOTE_REPO_PATH"] }
if (-not $RemoteUser) { $RemoteUser = $envValues["REMOTE_USER"] }
if (-not $SshKeyName) { $SshKeyName = $envValues["SSH_KEY_NAME"] }

if (-not $PreviewHost -or -not $RemoteRepoPath) {
    Write-Error "PreviewHost/RemoteRepoPath is missing. Configure dev-workflow.env, pass -PreviewHost/-RemoteRepoPath, or run scripts/init.mjs."
    exit 1
}

if (-not $Branch) {
    $Branch = (git symbolic-ref --quiet --short HEAD)
    if ($LASTEXITCODE -ne 0 -or -not $Branch) {
        Write-Error "-Branch was not provided and HEAD is detached, so the branch cannot be inferred."
        exit 1
    }
}

# Branch names and repository paths are inserted into a single-quoted remote shell
# command. Validate them so quotes or metacharacters cannot escape that boundary.
if ($Branch -notmatch '^[A-Za-z0-9._/-]+$') {
    Write-Error "Branch '$Branch' contains unsafe characters and was rejected."
    exit 1
}
foreach ($ch in @("'", '"', ';', '&', '|', '<', '>', '`', '$', '(', ')', "`n", "`r")) {
    if ($RemoteRepoPath.Contains($ch)) {
        Write-Error "REMOTE_REPO_PATH contains unsafe characters and was rejected: $RemoteRepoPath"
        exit 1
    }
}

# Honor REMOTE_USER and SSH_KEY_NAME when configured by init. Otherwise use the
# bare host and let ~/.ssh/config resolve the user and key. See
# docs/architecture/dev-workflow.md.
$target = if ($RemoteUser) { "$RemoteUser@$PreviewHost" } else { $PreviewHost }
$sshArgs = @()
if ($SshKeyName) {
    $keyPath = Join-Path $HOME ".ssh/$SshKeyName"
    $sshArgs += @("-i", $keyPath, "-o", "IdentitiesOnly=yes")
}

Write-Host "== [restart-remote] restarting preview on $target over SSH (branch $Branch) =="
ssh @sshArgs $target "cd '$RemoteRepoPath' && ./scripts/dev/preview.sh restart '$Branch'"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Remote preview.sh restart failed with exit code $LASTEXITCODE."
    exit 1
}

Write-Host "== [restart-remote] complete =="
